spring.application.name=admin-service
server.port=8090
spring.main.allow-circular-references=true

spring.datasource.url=jdbc:mysql://localhost:3306/admin_service
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#for logger 
logging.level.com.dailycodebuffer = INFO
logging.file.name = appLog.log
