spring.application.name=pickup-service
server.port=8086
spring.data.mongodb.uri=mongodb://localhost:27017/pickup-service

#For Payment
STRIPE_SECRET_KEY=sk_test_51NIOVESJkYBRGgMn7TpACPG8HQfJuOcdwQfbJA4WgGrom1cT5Z26iA1xV4oRfgVoqLyLu32WT0vntfyaPWlXfaig00TUCqoxvr