spring.application.name=order-service
server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017/order-service


##Adding eureka clint config externaly using config server
spring.config.import=optional:configserver:http://localhost:8085


###This for mailing purpose
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahuldipakjadhav16@gmail.com
spring.mail.password=fdwdgzmkrxrreeeq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true