spring.application.name=doctor-service
server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017/doctor_Service


##Adding eureka clint config externaly using config server
spring.config.import=optional:configserver:http://localhost:8085
