spring.application.name=doctor-service
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/doctor_Service

spring.main.allow-circular-references=true

#for logger 
logging.level.com.dailycodebuffer = INFO


logging.pattern.console=%d [%level] %c{1.} [%t] %m%n
logging.file.name = appLog.log
logging.pattern.file=%d [%level] %c{1.} [%t] %m%n

eureka.instance.prefer-ip-address=true

###This for mailing purpose
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahuldipakjadhav16@gmail.com
spring.mail.password=fdwdgzmkrxrreeeq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

