server.port:8085
spring.application.name=config-server



eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka




##USing this for config file and exporting to clients
spring.cloud.config.server.git.uri=file:///C:/Users/rahul/Desktop/PMS/External-Config-Files
