spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: ADMIN-SERVICE
          uri: http://localhost:8090/
          predicates:
            - Path=/adminOprations/**

        - id: DOCTOR-SERVICE
          uri: http://localhost:8081/
          predicates:
            - Path=/doctor/**,/registerDoctor/**

        - id: PICKUP-SERVICE
          uri: http://localhost:8086/
          predicates:
            - Path=/pickupAdmin/**,/pickupDoctor/**,/payment/**

        - id: ORDER-SERVICE
          uri: http://localhost:8083/
          predicates:
            - Path=/verifyOrder/**,/orderService/**

        - id: DRUG-INVENTORY
          uri: http://localhost:8082/
          predicates:
            - Path=/drugs/**,/stock/**
